function result = is_winner(board, turn)
    result = board(1, 1) == board(1, 2) == board(1, 3) == turn || ...
            board(2, 1) == board(2, 2) == board(2, 3) == turn || ...
            board(3, 1) == board(3, 2) == board(3, 3) == turn || ...
            board(1, 1) == board(2, 1) == board(3, 1) == turn || ...
            board(1, 2) == board(2, 2) == board(3, 2) == turn || ...
            board(1, 1) == board(2, 2) == board(3, 3) == turn || ...
            board(1, 3) == board(2, 2) == board(3, 1) == turn; 
end
